theme: jekyll-theme-cayman
title: Welcome to the 4MGT french courses my friends !
description: If you like to lose time, just read the fucking chapters.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty
show_downloads: true
homePage: true
